services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "9080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      - user-service
      - product-service
      - order-service
      - eureka-server

  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8761/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  eureka-client:
    build: ./client
    depends_on:
      - eureka-server

  product-service:
    build: ./product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/productservicedb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=cokgizlisifre
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
    depends_on:
      - eureka-server
      - mysql-db

  user-service:
    build: ./user-service
    depends_on:
      - eureka-server
      - mysql-db-2

  order-service:
    build: ./order-service
    depends_on:
      - eureka-server
      - mysql-db-3

  mysql-db:
    image: mysql:8.0
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=productservicedb
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pcokgizlisifre"]
      timeout: 20s
      retries: 10

  mysql-db-2:
    image: mysql:8.0
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=userservicedb
    volumes:
      - mysql_data_2:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pcokgizlisifre"]
      timeout: 20s
      retries: 10

  mysql-db-3:
    image: mysql:8.0
    ports:
      - "33063:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=cokgizlisifre
      - MYSQL_DATABASE=orderservicedb
    volumes:
      - mysql_data_3:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-uroot", "-pcokgizlisifre"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
  mysql_data_2:
  mysql_data_3: